Package: libjpeg
Maintainer: Marmalade Package Team <packages@ideaworkslabs.com>
Mkbs: libjpeg.mkb
Libraries: jpeg
Description:
 The Independent JPEG Group's JPEG library is a library for handling
 JPEG files.
Contents-Source:
 - README.rst
 - libjpeg.mkb
 - libjpeg.mkf
 - jconfig.h
 - example/data/splash.jpg
 - example/data/app.icf
 - example/libjpeg_example.cpp
 - example/libjpeg_example.mkb
Contents:
 - upstream/jpeglib.h : h/jpeglib.h
 - upstream/jerror.h : h/jerror.h
 - upstream/jpegint.h : h/jpegint.h
 - upstream/jmorecfg.h : h/jmorecfg.h
 - jconfig.h : h/jconfig.h
