#!/bin/sh

#cmake -DCMAKE_C_COMPILER=/usr/lib/distcc/bin/gcc-4.8.1 -DCMAKE_CXX_COMPILER=/usr/lib/distcc/bin/g++-4.8.1

cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DASSIMP_BUILD_STATIC_LIB=ON -DASSIMP_ENABLE_BOOST_WORKAROUND=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DASSIMP_BUILD_NO_OWN_ZLIB=ON
